services:
  web:
    build:
      context: .  # Root context for multi-stage Dockerfile
      dockerfile: Dockerfile.web  # Path to web Dockerfile in the root
    ports:
      - "8000:8000"
    environment:
      MODEL_SERVER: "http://tensorflow:8501"
      PYTHONPATH: "/app"
      PORT: "8000"
    depends_on:
      - tensorflow

  tensorflow:
    build:
      context: .  # Root context for the TensorFlow Dockerfile
      dockerfile: Dockerfile.tensorflow  # Path to TensorFlow Dockerfile in the root
    ports:
      - "8501:8501"
