services:
  web:
    build:
      context: .          # Use the root context for multi-stage Dockerfile
      dockerfile: server/Dockerfile   # Path to the new Dockerfile
    ports:
      - "8000:8000"
    environment:
      MODEL_SERVER: "http://tensorflow:8501"
      PYTHONPATH: "/app"
      PORT: "8000"
    depends_on:
      - tensorflow

  tensorflow:
    build:
      context: ./MLmodel
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
