services:
  web:
    build:
      context: .  # Root context for multi-stage Dockerfile
      dockerfile: Dockerfile.web  # Path to web Dockerfile in the root
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: "/app"
      PORT: "8000"