name: Capstone
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.2
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libffi=3.4.4
  - libsodium=1.0.18
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.3.1
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.2.2
  - prompt-toolkit=3.0.47
  - psutil=5.9.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.12.4
  - pywin32=305
  - pyzmq=25.1.2
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - ucrt=10.0.22621.0
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.1
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - dataclasses==0.6
      - filelock==3.15.4
      - flatbuffers==24.3.25
      - fluidsynth==0.2
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.66.1
      - h5py==3.11.0
      - idna==3.8
      - imageio==2.35.1
      - jinja2==3.1.4
      - keras==3.5.0
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mido==1.3.2
      - mido-fix==1.2.12
      - ml-dtypes==0.4.0
      - mpmath==1.3.0
      - musicpy==6.92
      - namex==0.0.8
      - networkx==3.3
      - numpy==1.26.4
      - opt-einsum==3.3.0
      - optree==0.12.1
      - packaging==23.2
      - pandas==2.2.2
      - pillow==10.4.0
      - pretty-midi==0.2.10
      - protobuf==4.25.4
      - pygame==2.6.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.32.3
      - rich==13.8.0
      - scikit-image==0.24.0
      - scipy==1.14.1
      - seaborn==0.13.2
      - sympy==1.13.2
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-intel==2.17.0
      - termcolor==2.4.0
      - tifffile==2024.8.30
      - torch==2.4.0
      - torchaudio==2.4.0
      - tzdata==2024.1
      - urllib3==2.2.2
      - werkzeug==3.0.4
      - wrapt==1.16.0

